### ISSUE TITLE
Wrong voltage reading with NCT6775

### ISSUE THREAD

**Issue by isaacgr** [groeck/nct6775#43]
Currently I get the following output when I run sensors after installing the nct6775 module:

Vcore:                  +0.89 V  (min =  +0.00 V, max =  +1.74 V)
in1:                    +1.01 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
AVCC:                   +3.28 V  (min =  +2.98 V, max =  +3.63 V)
+3.3V:                  +3.28 V  (min =  +2.98 V, max =  +3.63 V)
in4:                    +1.02 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in5:                    +1.97 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in6:                    +0.00 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
3VSB:                   +3.46 V  (min =  +2.98 V, max =  +3.63 V)
Vbat:                   +3.38 V  (min =  +2.70 V, max =  +3.63 V)
in9:                    +1.02 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in10:                   +0.00 V  (min =  +0.00 V, max =  +0.00 V)
in11:                   +0.86 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in12:                   +0.00 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in13:                   +0.60 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in14:                   +0.00 V  (min =  +0.00 V, max =  +0.00 V)  ALARM

I think it may be a scaling issue since when I add `label in1 "+12V"
` under the nct6775 chip in /etc/sensors3.conf it gives a reading of 1.01V. Any advice on how to scale these values correctly?

**Comment by groeck** [comment]
10/12/14 seem to be unused. For the others, the only means to find out would be to monitor the voltages for a while, write down any fluctuations, then go into the bios and find matching (scaled) voltages.
