### ISSUE TITLE
acpi_check_resource_conflict() will stop the driver working when conflicting

### ISSUE THREAD

**Issue by nuvcs10** [groeck/nct6775#52]
When BIOS defines an OperationRegion in ACPI table with the same I/O range used by the driver, 
the following code in this driver will stop the driver working:

static int __init sensors_nct6775_init(void){
    ...
    err = acpi_check_resource_conflict(&res);
    if (err) {
        ...
	continue;
    }
}

This case happens in some motherboards,
Could the code be modified as "only detect the conflict and print warning message without stop working"?
That will be some code like this:
static int __init sensors_nct6775_init(void){
    ...
    err = acpi_check_resource_conflict(&res);
    if (err) {
        ...
        //print some warning message here
    }
}
Thanks a lot.

**Comment by groeck** [comment]
You will have to boot with acpi_enforce_resources=lax.
